#!/bin/bash
#SBATCH --nodes=1
#SBATCH --gpus-per-node=4
#SBATCH --time=2-0
#SBATCH --partition=single
#SBATCH --job-name=elk_sweep_alpha
# This script was generated by sweep-script-gen.py

# [Variant(name='net', flag='--net', values=['ccs', 'eigen']), Variant(name='norm', flag='--norm', values=['burns', None]), Variant(name='per probe prompt', flag='--probe_per_prompt', values=['True', 'False']), Variant(name='prompt indices', flag='--prompt_indices', values=['1', None]), Variant(name='neg_cov_weight', flag='--neg_cov_weight', values=[None, 0, 0.5, 1]), Variant(name='loss', flag='--loss', values=['ccs_prompt_var', None]), Variant(name='visualize', flag='--visualize', values=[True])]

# --models sshleifer/tiny-gpt2
# --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte'

i=0
while [[ -e not-133-sweep-out-$i.txt ]] ; do
    let i++
done
filename="not-133-sweep-out-$i.txt"
exec > $filename 2>&1

j=0
while [[ -e commands_status-$j.csv ]] ; do
    let j++
done
csv_file="commands_status-$j.csv"
echo "idx,status,command" > $csv_file
set -e

# cd ../elk
commands=( \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=ccs --norm=burns --probe_per_prompt=True --prompt_indices=1 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=ccs --norm=burns --probe_per_prompt=True --loss=ccs_prompt_var --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=ccs --norm=burns --probe_per_prompt=True --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=ccs --norm=burns --probe_per_prompt=False --prompt_indices=1 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=ccs --norm=burns --probe_per_prompt=False --loss=ccs_prompt_var --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=ccs --norm=burns --probe_per_prompt=False --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=ccs --probe_per_prompt=True --prompt_indices=1 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=ccs --probe_per_prompt=True --loss=ccs_prompt_var --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=ccs --probe_per_prompt=True --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=ccs --probe_per_prompt=False --prompt_indices=1 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=ccs --probe_per_prompt=False --loss=ccs_prompt_var --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=ccs --probe_per_prompt=False --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=eigen --probe_per_prompt=True --prompt_indices=1 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=eigen --probe_per_prompt=True --prompt_indices=1 --neg_cov_weight=0 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=eigen --probe_per_prompt=True --prompt_indices=1 --neg_cov_weight=0.5 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=eigen --probe_per_prompt=True --prompt_indices=1 --neg_cov_weight=1 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=eigen --probe_per_prompt=True --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=eigen --probe_per_prompt=True --neg_cov_weight=0 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=eigen --probe_per_prompt=True --neg_cov_weight=0.5 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=eigen --probe_per_prompt=True --neg_cov_weight=1 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=eigen --probe_per_prompt=False --prompt_indices=1 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=eigen --probe_per_prompt=False --prompt_indices=1 --neg_cov_weight=0 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=eigen --probe_per_prompt=False --prompt_indices=1 --neg_cov_weight=0.5 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=eigen --probe_per_prompt=False --prompt_indices=1 --neg_cov_weight=1 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=eigen --probe_per_prompt=False --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=eigen --probe_per_prompt=False --neg_cov_weight=0 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=eigen --probe_per_prompt=False --neg_cov_weight=0.5 --visualize=True --num_gpus 4 --max_examples 10 10" \
"elk sweep --models sshleifer/tiny-gpt2 --datasets 'ag_news' 'amazon_polarity' 'dbpedia_14' 'glue:qnli' 'imdb' 'piqa' 'super_glue:boolq' 'super_glue:copa' 'super_glue:rte' --binarize --net=eigen --probe_per_prompt=False --neg_cov_weight=1 --visualize=True --num_gpus 4 --max_examples 10 10" \
)


idx=0
for command in "${commands[@]}"; do
    echo "$idx,NOT STARTED,$command" >> $csv_file
    ((idx=idx+1))
done

len=${#commands[@]}
for ((idx=0;idx<len;idx++)); do
    command=${commands[$idx]}
    sed -i "s|$idx,NOT STARTED|$idx,RUNNING|g" $csv_file
    echo "Running command: $command"
    curl -d "Sweep [$idx]: $command" ntfy.sh/derpy
    if ! eval "$command"; then
        sed -i "s|$idx,RUNNING|$idx,ERROR|g" $csv_file
        echo "Error occurred: Failed to execute command: $command"
        curl -d "Error occurred: Failed to execute command: $command" ntfy.sh/derpy
        break
    else
        sed -i "s|$idx,RUNNING|$idx,DONE|g" $csv_file
        echo "Command completed successfully: $command"
        curl -d "Command completed successfully: $command" ntfy.sh/derpy
    fi
done
echo 'All combinations completed.'
